### ISSUE TITLE
Updating for mkdocs 0.17 compatibility

### ISSUE THREAD

**Issue by taysu** [rfjakob/gocryptfs-website#3]
I was about to submit an addition to the documentation but found that the latest version of mkdocs doesn't seem to be compatible with this repository, mainly due to a number of significant changes the mkdocs developers made to the way custom themes work in 0.16/0.17:

http://www.mkdocs.org/about/release-notes/#theme-customization-1164
http://www.mkdocs.org/about/release-notes/#previously-deprecated-template-variables-removed-1168
http://www.mkdocs.org/about/release-notes/#increased-template-customization-607

I'd be more than willing to try and bring this repo up to date with the latest release. I was going to copy the latest version of the readthedocs theme from the mkdocs repo and then apply your changes again, making adjustments where necessary (for example, using the block system they've introduced). 

Would this be a welcome chunk of work? I just wanted to double check in case you were thinking of moving to a different system/approach, in which case this work would be a bit redundant.

Thanks!

Andy

**Comment by rfjakob** [comment]
Looks like it's already throwing warnings on 0.16.3 as well:
```
0 jakob@brikett:~/gocryptfs-website$ mkdocs -V
mkdocs, version 0.16.3
0 jakob@brikett:~/gocryptfs-website$ make
git pull
Already up-to-date.
LC_ALL=C.UTF-8 LANG=C.UTF-8 mkdocs build --clean
INFO    -  Cleaning site directory 
INFO    -  Building documentation to directory: /home/jakob/gocryptfs-website/site 
WARNING -  Template variable warning: 'favicon' is being deprecated and will not be available in a future version. Use '{{ base_url }}/img/favicon.ico' instead. 
WARNING -  Template variable warning: 'current_page' is being deprecated and will not be available in a future version. Use 'page' instead. 
WARNING -  Template variable warning: 'page_title' is being deprecated and will not be available in a future version. Use 'page.title' instead. 
WARNING -  Template variable warning: 'homepage_url' is being deprecated and will not be available in a future version. Use 'nav.homepage.url' instead. 
WARNING -  Template variable warning: 'site_name' is being deprecated and will not be available in a future version. Use 'config.site_name' instead. 
WARNING -  Template variable warning: 'toc' is being deprecated and will not be available in a future version. Use 'page.toc' instead. 
WARNING -  Template variable warning: 'next_page' is being deprecated and will not be available in a future version. Use 'page.next_page' instead. 
WARNING -  Template variable warning: 'previous_page' is being deprecated and will not be available in a future version. Use 'page.previous_page' instead. 
WARNING -  Template variable warning: 'copyright' is being deprecated and will not be available in a future version. Use 'config.copyright' instead. 
WARNING -  Template variable warning: 'content' is being deprecated and will not be available in a future version. Use 'page.content' instead. 
cp -af htaccess site/.htaccess
```
Yes, updating the template would be very welcome!
Also, I'm fine it if does not look 100% like the old site.

**Comment by taysu** [comment]
Changes merged in https://github.com/rfjakob/gocryptfs-website/pull/4, closing :)
